let hset : type =>
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  let foo : ? => ? in
  `bool
